### ISSUE TITLE
It tooks more than 1 hour/push.

### ISSUE THREAD

**Issue by tvvocold** [StartledPhoenix/openshift-diy-cachet#2]
Till now, i had change the .md file twice and push it 3 times, LOL.
Anyway to simplify the build?

Update:
Now i got this in last push.
```
remote: /tmp/build/php-5.5.23 /tmp/build /var/lib/openshift/5520d3615973cad80c0
002a
remote: Compiling PHP.
remote: make: *** No rule to make target `/tmp/build/php-5.5.23/ext/opcache/Zen
Accelerator.c', needed by `ext/opcache/ZendAccelerator.lo'.  Stop.
remote: An error occurred executing 'gear postreceive' (exit code: 2)
remote: Error message: CLIENT_ERROR: Failed to execute action hook 'build' for
520d3615973cad80c00002a application cachet
remote:
remote: For more details about the problem, try running the command again with
he '--trace' option.
```

**Comment by tvvocold** [comment]
@jasonbrooks Can u help us?

**Comment by tvvocold** [comment]
OOps,looks like i am in wrong repo, fixed in https://github.com/StartledPhoenix/openshift-cachet

**Comment by StartledPhoenix** [comment]
@tvvocold The push sometimes does that, just delete it and create a new VM.

Meanwhile, the deploy button currently points to the Cachet repositories and is waiting for a pull request (https://github.com/cachethq/Cachet/pull/562) to be accepted by the developer. Once it is accepted, the button will work.
